name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch if it's different
  pull_request:
    branches:
      - main  # Change this to your main branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest  # Add your test command here

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag sabarina134/mlapp:${{ github.sha }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Add your Docker Hub username as a secret
        password: ${{ secrets.DOCKER_PASSWORD }}  # Add your Docker Hub password as a secret

    - name: Push Docker image
      run: |
        docker push sabarina134/mlapp:${{ github.sha }}
